export const CREATE_TWIT_REQUEST="CREATE_TWIT_REQUEST";
export const CREATE_TWIT_SUCCESS="CREATE_TWIT_SUCCESS";
export const CREATE_TWIT_FAILURE="CREATE_TWIT_FAILURE";

export const DELETE_TWIT_REQUEST="DELETE_TWIT_REQUEST";
export const DELETE_TWIT_SUCCESS="DELETE_TWIT_SUCCESS";
export const DELETE_TWIT_FAILURE="DELETE_TWIT_FAILURE";

export const GET_USERS_TWIT_REQUEST="GET_USERS_TWIT_REQUEST";
export const GET_USERS_TWIT_SUCCESS="GET_USERS_TWIT_SUCCESS";
export const GET_USERS_TWIT_FAILURE="GET_USERS_TWIT_FAILURE";

export const USER_LIKE_TWIT_REQUEST="USER_LIKE_TWIT_REQUEST";
export const USER_LIKE_TWIT_SUCCESS="USER_LIKE_TWIT_SUCCESS";
export const USER_LIKE_TWIT_FAILURE="USER_LIKE_TWIT_FAILURE";

export const GET_ALL_TWIT_REQUEST="GET_ALL_TWIT_REQUEST";
export const GET_ALL_TWIT_SUCCESS="GET_ALL_TWIT_SUCCESS";
export const GET_ALL_TWIT_FAILURE="GET_ALL_TWIT_FAILURE";

export const LIKE_TWIT_REQUEST="LIKE_TWIT_REQUEST";
export const LIKE_TWIT_SUCCESS="LIKE_TWIT_SUCCESS";
export const LIKE_TWIT_FAILURE="LIKE_TWIT_FAILURE";

export const FIND_TWIT_BY_ID_REQUEST="FIND_TWIT_BY_ID_REQUEST";
export const FIND_TWIT_BY_ID_SUCCESS="FIND_TWIT_BY_ID_SUCCESS";
export const FIND_TWIT_BY_ID_FAILURE="FIND_TWIT_BY_ID_FAILURE";

export const REPLY_TWIT_REQUEST="REPLY_TWIT_REQUEST";
export const REPLY_TWIT_SUCCESS="REPLY_TWIT_SUCCESS";
export const REPLY_TWIT_FAILURE="REPLY_TWIT_FAILURE";

export const RETWIT_REQUEST="RETWIT_REQUEST";
export const RETWIT_SUCCESS="RETWIT_SUCCESS";
export const RETWIT_FAILURE="RETWIT_FAILURE";